language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: PHPCS_TEST=1
    - php: 7.0
      env: SS4=1

before_script:
 - phpenv rehash
 - export PATH=~/.composer/vendor/bin:$PATH
 - composer validate
 - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi
 - composer self-update || true
 - "if [ \"$SS4\" = \"1\" ]; then composer require 'silverstripe/framework:4.0.x-dev'; fi"
 - "if [ \"$SS4\" = \"1\" ]; then composer require 'silverstripe/config:1.0.x-dev'; fi"
 - composer install --prefer-dist

script:
 - vendor/bin/phpunit
 - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
